install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
    - sudo apt-get install chktex
    - sudo apt-get install parallel

script:
    - chktex -W # Print version information.
    - sh getOrder.sh master.tex | parallel 'chktex -l .chktexrc -I0 {} 2>/dev/null' | tee lint.out
    # If lint output is non-empty report an error.
    - test ! -s lint.out
