install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
    - sudo apt-get install chktex

script:
    - chktex -W # Print version information.
    - chktex -l .chktexrc -i0 master.tex 2>/dev/null | tee lint.out
    # If lint output is non-empty report an error.
    - test ! -s lint.out
    - find ./chapters -maxdepth 1 -name '*.tex' | xargs chktex -l .chktexrc 2>/dev/null | tee lint.out
    - test ! -s lint.out
